### ISSUE TITLE
in get_last_checkpoint     assert len(ckpts) > 0

### ISSUE THREAD

**Issue by ahworld22** [ShanWang-Shan/SIBCL#3]
Hello
!When I start running the train.py to train the Kitti,it has the error like this:
[08/21/2024 09:33:35 pixloc INFO] Starting experiment kitti
Traceback (most recent call last):
  File "D:\daxue\异构\跨视角地图融合复现\SIBCL-main\pixloc\pixlib\train.py", line 465, in <module>
    main_worker(0, conf, output_dir, args)
  File "D:\daxue\异构\跨视角地图融合复现\SIBCL-main\pixloc\pixlib\train.py", line 414, in main_worker
    training(rank, conf, output_dir, args)
  File "D:\daxue\异构\跨视角地图融合复现\SIBCL-main\pixloc\pixlib\train.py", line 160, in training
    init_cp = get_last_checkpoint(args.experiment, allow_interrupted=False)
  File "D:\daxue\异构\跨视角地图融合复现\SIBCL-main\pixloc\pixlib\utils\experiments.py", line 35, in get_last_checkpoint
    assert len(ckpts) > 0
AssertionError

**Comment by ShanWang-Shan** [comment]
This log indicates that the pretrained model weights are missing from your experiment folder. Please download the provided model weights and verify the name of your experiment folder.

**Comment by ahworld22** [comment]
> This log indicates that the pretrained model weights are missing from your experiment folder. Please download the provided model weights and verify the name of your experiment folder.

Ok, so should I download the weight model here:
![image](https://github.com/user-attachments/assets/b9713fa9-988f-4d3a-8ebd-e784dee2cc64)? Where should I put it after downloading? Also, when I changed restore to false, it ran as follows and then stopped, I wonder why.
[log.txt](https://github.com/user-attachments/files/16737179/log.txt)

**Comment by ShanWang-Shan** [comment]
Yes, please download weights and place the weights in your experiment folder. You can set your experiment folder; for example, create an 'experiment' folder named 'kitti' under 'TRAINING_PATH'(default: 'SIBCL/outputs/training'). Please try debugging your folder settings to resolve the problem.
line418: parser.add_argument('--experiment', type=str, default='kitti')
line431: output_dir = Path(TRAINING_PATH, args.experiment)

**Comment by ahworld22** [comment]
> Yes, please download weights and place the weights in your experiment folder. You can set your experiment folder; for example, create an 'experiment' folder named 'kitti' under 'TRAINING_PATH'(default: 'SIBCL/outputs/training'). Please try debugging your folder settings to resolve the problem. line418: parser.add_argument('--experiment', type=str, default='kitti') line431: output_dir = Path(TRAINING_PATH, args.experiment)

But if I set resotore as false, it doesn't need the weights, right?

**Comment by ShanWang-Shan** [comment]
I have not trained from scratch; starting from a pre-trained weight is highly recommended as it will speed up your training process. If you choose to train from scratch, you may need to debug step by step to identify why it stopped in your environment.

**Comment by ahworld22** [comment]
> I have not trained from scratch; starting from a pre-trained weight is highly recommended as it will speed up your training process. If you choose to train from scratch, you may need to debug step by step to identify why it stopped in your environment.

OK .So I can put my dataset and weights all in the  'SIBCL/outputs/training'

**Comment by ShanWang-Shan** [comment]
You can configure your dataset path, for example, by setting it in line 23: root_dir = "/data/dataset/Kitti" within the file pixloc/pixlib/datasets/kitti.py.

**Comment by ahworld22** [comment]
> 您可以配置数据集路径，例如，在文件 pixloc/pixlib/datasets/kitti.py 中的第 23 行中设置它： root_dir = “/data/dataset/Kitti”。

YES, I set like that.But it always says it could not found the "checkpoint_best.tar".I change the "best" to "71" and than it works.But it stop at "pred = model(data)" and didn't raise any error.

**Comment by ShanWang-Shan** [comment]
I understand what you're struggling with now. During training, when I started from a specific weight, I copied checkpoint_count.tar to checkpoint_best.tar, and both of these files are located in the experiments folder.

**Comment by ahworld22** [comment]
> I understand what you're struggling with now. During training, when I started from a specific weight, I copied checkpoint_count.tar to checkpoint_best.tar, and both of these files are located in the experiments folder.

It seems like a new problem has raised:
![image](https://github.com/user-attachments/assets/f9a820a5-e828-40ea-883e-64a0a0dc42d0)

**Comment by QianXiaoo** [comment]
> > I understand what you're struggling with now. During training, when I started from a specific weight, I copied checkpoint_count.tar to checkpoint_best.tar, and both of these files are located in the experiments folder.
> 
> It seems like a new problem has raised: ![image](https://private-user-images.githubusercontent.com/155041428/363036323-f9a820a5-e828-40ea-883e-64a0a0dc42d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MzI4NTEsIm5iZiI6MTczNTYzMjU1MSwicGF0aCI6Ii8xNTUwNDE0MjgvMzYzMDM2MzIzLWY5YTgyMGE1LWU4MjgtNDBlYS04ODNlLTY0YTBhMGRjNDJkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQwODA5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWNiNzRlNDkwN2M1MDk5MjM0YWEzODZiZDZkZWE5YWJjY2MzM2M3YmFjZjJmZjAwNDdlZDRiMWZiZjg0YTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.etCs_Dsr5IiRwLYkz5L8WeTrbT4g_GE9xSw2ubGWxBc)

Hello, have you obtained the aerial images from the KITTI dataset for this paper?

**Comment by ShanWang-Shan** [comment]
I couldn't reproduce your issue. Please confirm your Python and NumPy versions. I'm using Python 3.9 and NumPy 2.0.2.
